name = "daotrack-worker"
main = "src/index.js"
compatibility_date = "2023-01-01"

[vars]
BOT_TOKEN = "7316296656:AAG-jlt8tgqzMKeVrBnqH3558hUBWqrAwpk"  # Will be overridden by environment
CHAT_ID = "-1002370104136"    # Will be overridden by environment
API_KEY = "a2e2c76b-a4cf-4357-8d95-0939d7e851f8"    # Will be overridden by environment

[[kv_namespaces]]
binding = "TOKEN_BUYS_10"
id = "eede25f4efff4c6a90c3fb40ce69540b"

[observability]
enabled = true
head_sampling_rate = 1 